workflows:
  android-release:
    name: LISA APK Build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build Release APK
        script: flutter build apk --release --split-per-abi --target lib/main.dart

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - labibhasan4429@gmail.com
        notify:
          success: true
          failure: true
